# Generated by Django 4.2.27 on 2026-01-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptbox', '0002_organizationmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='visibility',
            field=models.CharField(choices=[('PRIVATE', 'Private'), ('TEAM', 'Team')], default='PRIVATE', max_length=20),
        ),
    ]
