# Generated by Django 6.0.1 on 2026-01-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptbox', '0004_folder_prompt_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='visibility',
            field=models.CharField(choices=[('PRIVATE', 'Private'), ('TEAM', 'Team'), ('PUBLIC', 'Public')], default='PRIVATE', max_length=20),
        ),
    ]
