# Generated by Django 6.0 on 2026-02-13 14:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptbox', '0005_alter_prompt_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('change_summary', models.CharField(max_length=255)),
                ('snapshot', models.JSONField()),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt_changes', to=settings.AUTH_USER_MODEL)),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='promptbox.prompt')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
